### ISSUE TITLE
Guild Point item remains in inventory after trade

### ISSUE THREAD

**Issue by T3RT1UM** [HomepointXI/Website#1]
Date & Time: 3/7/2018  7:19 PM

Client Version (use /ver in game): 30171223_0

Character Name: Kurare

Nation: Bastok

Job(level)/Sub Job(level): Thief99/Ninja49

NPC or Monster or item Name: Hemewmew

Zone name: Bastok Mines

Coordinates (use !where): X:120 Y:2 Z:-9 (110)

Item tool link (for items issues only):

Multi-boxing? (multiple clients on same connection): yes

Steps to reproduce: Traded requested item for Guild Points (Silence baghnakhs)

Any additional information:

**Comment by EpicTaru** [comment]
This ticket is in the wrong location, it needs to be on the issues tracker for the server (not the website).  Please re-submit it under that tracker.
