### ISSUE TITLE
Hachiryu Sune-ate coded?

### ISSUE THREAD

**Issue by valkus8712** [HomepointXI/Website#5]
**2/4/19  4:pm CST**:
**Hachiryu Sune-ate**:
http://homepointxi.com/db/items/11364/hachiryu_sune-ate
**No drop info on database**:
**check url**:
**all hachiryu gear peices available on database except boots   Hachiryu Sune-ate**:

**Comment by Heepster03** [comment]
Wrong place for this. Not a site issue.
