### ISSUE TITLE
Wrong URL in the Yaanei's page

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Website#6]
**Bug Date & Time**: 20210930
**Bug Name**:
**Bug Page/Url**: http://wiki.homepointxi.com/Yaanei
**Bug Information**: wrong url
**Steps To Reproduce The Bug**:
1. Jump to http://wiki.homepointxi.com/Yaanei
2. Click on "CLICK HERE FOR MOB INFORMATION!!!" at the bottom of this page
http://homepointxi.com/db/monsters/17658289/Yaanei
3. You will open the Warbler page.

1. Jump to http://wiki.homepointxi.com/Eccentric_Eve
2. Click on "CLICK HERE FOR MOB INFORMATION!!!" at the bottom of this page
3. You will open the Kukulkan page.

**Additional Information**:

**Comment by EpicTaru** [comment]
@Fragile2021 both issues resolved now.  Thanks for this ticket about both of them!
